# This is a basic workflow to help you get started with Actions
name: Build for MacOS

on: 
  push:
    branches:
      - onit_build_windows_ci_test_macos 

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      
      # Checkout project
      - uses: actions/checkout@v2

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE;
          ls;
